2023-03-02 21:30:15,809 INFO    StreamThr :478273 [internal.py:wandb_internal():90] W&B internal server running at pid: 478273, started at: 2023-03-02 21:30:15.809422
2023-03-02 21:30:15,810 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status
2023-03-02 21:30:15,813 INFO    WriterThread:478273 [datastore.py:open_for_write():85] open: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/run-3l07iz0b.wandb
2023-03-02 21:30:15,813 DEBUG   SenderThread:478273 [sender.py:send():336] send: header
2023-03-02 21:30:15,833 DEBUG   SenderThread:478273 [sender.py:send():336] send: run
2023-03-02 21:30:16,026 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: check_version
2023-03-02 21:30:16,075 INFO    SenderThread:478273 [dir_watcher.py:__init__():216] watching files in: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files
2023-03-02 21:30:16,075 INFO    SenderThread:478273 [sender.py:_start_run_threads():1070] run started: 3l07iz0b with start time 1677810615.81026
2023-03-02 21:30:16,075 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:16,075 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:16,075 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: check_version
2023-03-02 21:30:16,170 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: run_start
2023-03-02 21:30:16,175 DEBUG   HandlerThread:478273 [system_info.py:__init__():31] System info init
2023-03-02 21:30:16,175 DEBUG   HandlerThread:478273 [system_info.py:__init__():46] System info init done
2023-03-02 21:30:16,175 INFO    HandlerThread:478273 [system_monitor.py:start():151] Starting system monitor
2023-03-02 21:30:16,175 INFO    SystemMonitor:478273 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-03-02 21:30:16,175 INFO    HandlerThread:478273 [system_monitor.py:probe():172] Collecting system info
2023-03-02 21:30:16,176 INFO    SystemMonitor:478273 [interfaces.py:start():168] Started cpu
2023-03-02 21:30:16,176 INFO    SystemMonitor:478273 [interfaces.py:start():168] Started disk
2023-03-02 21:30:16,177 INFO    SystemMonitor:478273 [interfaces.py:start():168] Started gpu
2023-03-02 21:30:16,177 INFO    SystemMonitor:478273 [interfaces.py:start():168] Started memory
2023-03-02 21:30:16,177 INFO    SystemMonitor:478273 [interfaces.py:start():168] Started network
2023-03-02 21:30:16,224 DEBUG   HandlerThread:478273 [system_info.py:probe():195] Probing system
2023-03-02 21:30:16,225 DEBUG   HandlerThread:478273 [system_info.py:_probe_git():180] Probing git
2023-03-02 21:30:16,240 DEBUG   HandlerThread:478273 [system_info.py:_probe_git():188] Probing git done
2023-03-02 21:30:16,241 DEBUG   HandlerThread:478273 [system_info.py:probe():241] Probing system done
2023-03-02 21:30:16,241 DEBUG   HandlerThread:478273 [system_monitor.py:probe():181] {'os': 'Linux-5.15.0-60-generic-x86_64-with-debian-bullseye-sid', 'python': '3.7.0', 'heartbeatAt': '2023-03-03T02:30:16.224847', 'startedAt': '2023-03-03T02:30:15.801017', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'humanRL_gym_ple/modified_dqn_ple.py', 'codePath': 'humanRL_gym_ple/modified_dqn_ple.py', 'git': {'remote': 'https://github.com/rach0012/humanRL_prior_games.git', 'commit': 'c9fff26af5df3e1cdea023536da5fda114ba5c60'}, 'email': 'zhding@mail.ustc.edu.cn', 'root': '/home/quantumiracle/research/humanRL_prior_games', 'host': 'quantumiracle-XPS-8940', 'username': 'quantumiracle', 'executable': '/home/quantumiracle/anaconda3/envs/x/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3529.4548124999997, 'min': 800.0, 'max': 4825.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 4402.444, 'min': 800.0, 'max': 4900.0}, {'current': 4298.236, 'min': 800.0, 'max': 4900.0}, {'current': 4367.259, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 4402.549, 'min': 800.0, 'max': 4900.0}, {'current': 2500.0, 'min': 800.0, 'max': 4900.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}, {'current': 2500.0, 'min': 800.0, 'max': 4800.0}], 'disk': {'total': 915.3232879638672, 'used': 867.7159614562988}, 'gpu': 'NVIDIA GeForce RTX 3060 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Ti', 'memory_total': 8589934592}], 'memory': {'total': 62.483726501464844}}
2023-03-02 21:30:16,241 INFO    HandlerThread:478273 [system_monitor.py:probe():182] Finished collecting system info
2023-03-02 21:30:16,241 INFO    HandlerThread:478273 [system_monitor.py:probe():185] Publishing system info
2023-03-02 21:30:16,241 DEBUG   HandlerThread:478273 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-03-02 21:30:16,242 DEBUG   HandlerThread:478273 [system_info.py:_save_pip():67] Saving pip packages done
2023-03-02 21:30:16,242 DEBUG   HandlerThread:478273 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-03-02 21:30:17,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/requirements.txt
2023-03-02 21:30:17,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/conda-environment.yaml
2023-03-02 21:30:17,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/wandb-summary.json
2023-03-02 21:30:19,550 DEBUG   HandlerThread:478273 [system_info.py:_save_conda():86] Saving conda packages done
2023-03-02 21:30:19,550 DEBUG   HandlerThread:478273 [system_info.py:_save_code():89] Saving code
2023-03-02 21:30:19,556 DEBUG   HandlerThread:478273 [system_info.py:_save_code():110] Saving code done
2023-03-02 21:30:19,556 DEBUG   HandlerThread:478273 [system_info.py:_save_patches():127] Saving git patches
2023-03-02 21:30:19,587 DEBUG   HandlerThread:478273 [system_info.py:_save_patches():169] Saving git patches done
2023-03-02 21:30:19,587 INFO    HandlerThread:478273 [system_monitor.py:probe():187] Finished publishing system info
2023-03-02 21:30:19,591 DEBUG   SenderThread:478273 [sender.py:send():336] send: files
2023-03-02 21:30:19,591 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-metadata.json with policy now
2023-03-02 21:30:19,591 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file code/humanRL_gym_ple/modified_dqn_ple.py with policy now
2023-03-02 21:30:19,592 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file diff.patch with policy now
2023-03-02 21:30:19,597 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: stop_status
2023-03-02 21:30:19,597 DEBUG   SenderThread:478273 [sender.py:send():336] send: telemetry
2023-03-02 21:30:19,597 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: stop_status
2023-03-02 21:30:19,675 ERROR   Thread-12 :478273 [step_upload.py:_handle_event():142] Failed to upload file: /tmp/tmpj8z24ve3wandb/zqqava92-diff.patch
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
    job.run()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 62, in run
    self.push()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 113, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.
2023-03-02 21:30:19,679 ERROR   Thread-12 :478273 [step_upload.py:_handle_event():142] Failed to upload file: /tmp/tmpj8z24ve3wandb/h5tiska1-wandb-metadata.json
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
    job.run()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 62, in run
    self.push()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 113, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.
2023-03-02 21:30:19,679 ERROR   Thread-12 :478273 [step_upload.py:_handle_event():142] Failed to upload file: /tmp/tmpj8z24ve3wandb/jz9h8h6n-code/humanRL_gym_ple/modified_dqn_ple.py
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
    job.run()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 62, in run
    self.push()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 113, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.
2023-03-02 21:30:20,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/code/humanRL_gym_ple/modified_dqn_ple.py
2023-03-02 21:30:20,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/diff.patch
2023-03-02 21:30:20,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/wandb-metadata.json
2023-03-02 21:30:20,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:20,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/code
2023-03-02 21:30:20,076 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/code/humanRL_gym_ple
2023-03-02 21:30:21,262 INFO    HandlerThread:478273 [handler.py:handle_tbrecord():748] handling tbrecord: tbrecord {
  log_dir: "runs/smallGame"
  save: true
}
control {
  relay_id: "31763ae8a2da4613ac13b77e58a043b9"
}
_info {
  stream_id: "3l07iz0b"
}

2023-03-02 21:30:21,262 DEBUG   HandlerThread:478273 [config_util.py:dict_from_config_file():100] no default config file found in config-defaults.yaml
2023-03-02 21:30:21,293 DEBUG   SenderThread:478273 [sender.py:send():336] send: tbrecord
2023-03-02 21:30:21,294 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status_report
2023-03-02 21:30:22,065 DEBUG   SenderThread:478273 [sender.py:send():336] send: files
2023-03-02 21:30:22,065 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0 with policy live
2023-03-02 21:30:22,077 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:22,077 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_created():275] file/dir created: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
2023-03-02 21:30:22,153 ERROR   Thread-12 :478273 [step_upload.py:_handle_event():142] Failed to upload file: /tmp/tmpj8z24ve3wandb/7ixwy5or-events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
    job.run()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 62, in run
    self.push()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 113, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.
2023-03-02 21:30:24,078 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:26,448 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status_report
2023-03-02 21:30:28,079 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:30,080 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:31,456 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status_report
2023-03-02 21:30:32,081 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:34,082 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
2023-03-02 21:30:34,082 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:34,125 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,131 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,135 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,136 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,136 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,136 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,136 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,136 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,136 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,137 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,137 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,137 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,137 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,137 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,137 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,137 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,137 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,138 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,138 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,138 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,138 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,138 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,138 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,138 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,138 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,139 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,139 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,139 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,139 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,139 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,139 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,139 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,139 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,139 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,140 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,140 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,140 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,140 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,140 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,140 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,140 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,140 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,141 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,141 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,141 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,141 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,141 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,141 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,141 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,141 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,142 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,142 DEBUG   SenderThread:478273 [sender.py:send():336] send: history
2023-03-02 21:30:34,142 DEBUG   SenderThread:478273 [sender.py:send_request():363] send_request: summary_record
2023-03-02 21:30:34,142 INFO    SenderThread:478273 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-02 21:30:34,594 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:30:34,594 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:30:35,082 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/wandb-summary.json
2023-03-02 21:30:36,082 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:36,629 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status_report
2023-03-02 21:30:38,083 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:39,595 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:30:40,084 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:41,639 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status_report
2023-03-02 21:30:42,084 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:44,085 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:44,596 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:30:46,086 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:46,663 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: status_report
2023-03-02 21:30:46,747 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:30:46,747 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:30:47,948 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:30:47,948 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:30:48,086 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
2023-03-02 21:30:48,087 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/output.log
2023-03-02 21:30:49,597 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:30:50,433 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:30:50,433 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:30:50,433 INFO    SenderThread:478273 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-03-02 21:30:54,597 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:30:55,504 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:30:55,504 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:30:59,598 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:03,904 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:31:03,904 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:31:04,598 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:09,599 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:14,600 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:16,096 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
2023-03-02 21:31:16,178 DEBUG   SystemMonitor:478273 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-03-02 21:31:19,601 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:21,861 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:31:21,861 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:31:24,601 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:29,603 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:34,603 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:39,604 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:44,605 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:48,106 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
2023-03-02 21:31:48,211 ERROR   Thread-12 :478273 [step_upload.py:_handle_event():142] Failed to upload file: /tmp/tmpj8z24ve3wandb/dh1lf03h-events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
    job.run()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 62, in run
    self.push()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 113, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist quantumiracle/dqn_ple/3l07iz0b.
2023-03-02 21:31:49,605 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:54,606 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:31:57,963 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:31:57,963 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:31:59,608 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:04,608 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:09,609 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:14,610 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:19,611 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:22,117 INFO    Thread-13 :478273 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/files/events.out.tfevents.1677810621.quantumiracle-XPS-8940.478245.0
2023-03-02 21:32:24,612 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:29,613 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:34,613 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:39,614 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:44,615 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:49,616 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:54,617 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:32:59,618 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:33:04,619 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:33:09,417 ERROR   SenderThread:478273 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-02 21:33:09,418 ERROR   SenderThread:478273 [internal_api.py:execute():246] {"errors":[{"message":"run quantumiracle/dqn_ple/3l07iz0b was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-02 21:33:09,620 DEBUG   HandlerThread:478273 [handler.py:handle_request():144] handle_request: keepalive
2023-03-02 21:33:09,620 INFO    HandlerThread:478273 [handler.py:finish():841] shutting down handler
2023-03-02 21:33:10,183 INFO    WriterThread:478273 [datastore.py:close():299] close: /home/quantumiracle/research/humanRL_prior_games/wandb/run-20230302_213015-3l07iz0b/run-3l07iz0b.wandb
2023-03-02 21:33:15,762 ERROR   StreamThr :478273 [internal.py:wandb_internal():175] Thread SenderThread:
Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1597, in upsert_run
    **kwargs,
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 217, in gql
    **kwargs,
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 335, in _debounce
    self._sm.debounce()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 512, in debounce
    self._maybe_update_config(always=final)
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 489, in _maybe_update_config
    self._debounce_config()
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 519, in _debounce_config
    name=self._run.run_id, config=config_value_dict, **self._api_settings  # type: ignore
  File "/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/wandb/apis/normalize.py", line 28, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
